/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IContributionToken } from "./IContributionToken";
export type { RewardVault } from "./RewardVault";
